### PR TITLE
Added UCSBOrganization entity and repo, tested on local

### PR DESCRIPTION
**Pull request by moomoo02**
Worked on Issue #26 .  I created the Entity and Repository for UCSBOrganization.  I then tested it on local host as well as on heroku qa, and it worked.

### CODE REVIEW

**Comment by moomoo02** [comment]
Does anyone know what the codecov report is saying?

**Comment by moomoo02** [comment]
oh it seems fine now.

**Comment by moomoo2202** [comment]
Closed pull request, created a more updated branch with GET/POST and Tests

**Review by JohnK-mi — APPROVED** [review]
Entity has appropriate fields, and Repository properly extends CRUD Interface. Code is readable and well formatted as well as passes prerequisite checks.

**Review by kevin2hang — APPROVED** [review]
Code is clean and concise. Has proper variable names.

**Pull request merged**
